name: exams_system
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  random_string: ^2.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nasalization
      fonts:
        - asset: assets/fonts/nasalizationRg.ttf
    - family: BrandonGrotesque
      fonts:
        - asset: assets/fonts/brandonGrotesqueThin.ttf
          weight: 200
        - asset: assets/fonts/brandonGrotesqueLight.ttf
          weight: 300
        - asset: assets/fonts/brandonGrotesqueRegular.ttf
        - asset: assets/fonts/brandonGrotesqueMedium.ttf
          weight: 500
        - asset: assets/fonts/brandonGrotesqueBold.ttf
          weight: 700
        - asset: assets/fonts/brandonGrotesqueBlack.ttf
          weight: 900
